version: '2.18'

networks:
  app-tier:
    driver: bridge

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    networks:
      - app-tier
    links: 
      - database
    depends_on:
      - database
